name: Build and test on Windows

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
      - '.githooks/**'

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        # windows-2022 has MSVC 2022 installed:
        # https://github.com/actions/virtual-environments.
        # Only x64 is supported.
        os: [windows-2022]
        include:
          - os: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.2.x'

      - name: Use cmake
        run: cmake --version

      - name: Setup MSVC dev environment
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Build and test
        env:
          VCPKG_ROOT: "C:\\vcpkg"
        run: |
          cmake --workflow --preset windows-ci
